SublimeText/Terraform

- Terraform.YAML-tmLanguage
- Terraform.tmLanguage
I started my own .tmLanguage last night without realizing that there was one already. So I've incorporated the other syntax improvements I added (mainly numbers, maps, and language constants) and made some of yours more robust (it wasn't handling `resource "xxx" "a-b-c-d" {` properly).
Hopefully you guys like the improved highlighting :).
> More syntax highlighting

- Comments.tmPreferences
- Terraform.YAML-tmLanguage
- Terraform.tmLanguage
According to https://github.com/hashicorp/hcl/blob/master/README.md
single line comments can also start with `//`
> Add support for double slash comments

- Terraform.YAML-tmLanguage
- Terraform.tmLanguage
Many other Hashicorp tools use the same syntax as terraform files, and thus could use the same syntax highlighting.  I've added 1 additional file extension to include those files.
> Add .hcl as a highlighted file extention

- Terraform.YAML-tmLanguage
- Terraform.tmLanguage
> Fix detection of << end.

- Terraform.YAML-tmLanguage
- Terraform.tmLanguage
Full list on:
https://www.terraform.io/docs/configuration/interpolation.html#built-in-functions
Summary of changes:
**ADDED**
```
base64gzip
base64sha512
basename
bcrypt
chomp
coalescelist
contains
dirname
flatten
log
matchkeys
pow
sha512
urlencode
```
**REMOVED**
```
from     # This is not a built-in function. Not sure why it was defined
length   # was defined twice
```
> Add support to all built-in functions available on Terraform v0.10.3

- Terraform.tmLanguage
This should address the following issue:
https://github.com/alexlouden/Terraform.tmLanguage/issues/28
I can't be sure there aren't any side-effects, but locally tested as I also experienced this shows nothing out of the ordinary that I can see.
Recommend Squash-Merge, to avoid my lame commit messages.
> Syntax Highlight Correction for Regex's inside strings (See Issue #28)

- Terraform.sublime-syntax
This fixes a small bug which has been annoying me for some time, namely that `data` elements with a dash in their identifier weren't syntax highlighted correctly.
I've also updated the list of functions to contain all the new ones from Terraform 0.12.
> Minor fixes

- Symbols.tmPreferences
- Terraform.sublime-syntax
Adds symbol indexing for the following types of blocks:
- `resource`
- `data`
- `provider`
- `provisioner`
- `variable`
- `output`
- `module`
- `atlas`
These symbols will now be available for [symbol navigation](http://docs.sublimetext.info/en/latest/reference/symbols.html).
This requires adding a new `meta` scope ` meta.block.terraform` around all blocks — similar to how it was previously done for `resource` and `data` blocks (`meta.resource.terraform`).
> Add Symbol Indexing

- snippets/variable_empty.sublime-snippet
- snippets/variable_map.sublime-snippet
- snippets/variable_string.sublime-snippet
in 0.12 you no longer need to quote variable types, https://www.terraform.io/docs/configuration/variables.html. this pr simply removes the quotes from the variable snippets
> remove quotes around variable type in snippets

- Terraform.sublime-syntax
I noticed that the links to https://www.terraform.io/ were outdated so I checked them all individually and updated them.
> Update links to official docs on terraform.io

- .github/workflows/ci.yaml
An attempt to get the CI "unstuck", as suggested in https://github.com/alexlouden/Terraform.tmLanguage/pull/56#issuecomment-1898018046
> github: bump linux version to latest

- Terraform.YAML-tmLanguage
- Terraform.sublime-syntax
- Terraform.tmLanguage
Nomad files are configured against HCL too, this adds sublime text support for them.
> feat: Add nomad configuration support

- HCL.sublime-syntax
- Terraform-vars.sublime-syntax
- Terraform.sublime-syntax
Breaks compatibility with ST3.
> Use version: 2 for syntaxes

- Terraform.sublime-syntax
- syntax_test_terraform-vars.tfvars
- syntax_test_terraform.tf
I could imagine dispute about adding perceived types inside strings, but I find it very helpful.
> Add language constants to strings

- Terraform Plan.sublime-syntax
- syntax_test_terraform_plan.tfplan
> Add highlighting for Plan output

- JSON (Terraform).sublime-syntax
- Terraform.sublime-syntax
This commit turns JSON (Terraform) into a visible syntax as it has a file extension assigned.
Note: Hidden file causes A File Icon dummy to take precedence, breaking syntax highlighting.
To avoid it, absolute path is used to include _JSON (Terraform)_ syntax in Terraform.
> Make JSON (Terraform) visible

- JSON (Terraform).sublime-syntax
- Terraform.sublime-syntax
- tests/syntax_test_scope.tf
This PR...
1. adds ACL highlighting support to JSON values.
2. fixes string interpolation scopes within ACL variables.
- remove string but not variable scope.
> Improve ACL highlighting

- Terraform.sublime-syntax
- tests/syntax_test_scope.tf
This commit..
1. adds more detailed control keyword scopes to interpolation
2. scopes `in` `keyword.operator.iteration.in`
> More detailed control keywords in interpolations

- Terraform.sublime-syntax
- tests/syntax_test_scope.tf
This commit...
1. adds missing meta.brackets, meta.braces and meta.parens scopes
2. fixes inline for expressions vanishing meta scopes
3. fixes block and type related meta scope boundaries; avoid gaps or overlapping
> Fix bracket related meta scopes

- Indentation Rules.tmPreferences
- tests/syntax_test_reindent.tf
This commit makes sure all sorts of brackets are treated equally.
related with https://github.com/sublimehq/Packages/pull/4209
> Add basic indentation rules

- Terraform.sublime-syntax
- tests/syntax_test_scope.tf
This PR...
1. scopes namespaces in function calls `variable.namespace`
2. adds more detailed `meta.function-call.[identifier|arguments]` scopes.
3. adjusts tests accordingly
4. reformats list of built-in functions
> Impove function-call syntax

- Terraform.sublime-syntax
- tests/syntax_test_scope.tf
See also https://github.com/sublimehq/Packages/pull/4227 for a prior discussion of this.
> Scope `in` as `keyword.control` again

- Symbols - Indexed.tmPreferences
- Symbols - Local.tmPreferences
- Symbols.tmPreferences
- Terraform.sublime-syntax
- tests/syntax_test_scope.tf
- tests/syntax_test_symbol.tf
These should be scoped like other strings. They are declared as `StringLit` and generally function like strings with regards to escape sequences but do not permit template interpolation. (In fact, normal identifiers may also be used.)
Docs: https://developer.hashicorp.com/terraform/language/syntax/configuration#arguments-and-blocks
Spec:
1. https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#structural-elements
2. https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#template-expressions
> Apply string scopes to resource block identifiers
